# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19fbdb522344ecac4946059d045e0087ca82d1cd86b28b3fa519c42b946d4017abcfebce9e211e82ca7b22052c177ac2c32e5f6f61fe327597dbfe0c8eac0640

test:
  secret_key_base: f022aa104d39ffa0df0a31c6776f71a16ad9790f0736c78f118f30b97dbd8a935ddb24e0c045eea3cf2f4fb16fc0d80b7109b1d5f50d8bd734bc1075f49b7b75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
